### ISSUE TITLE
3.6: Composite Indexes always re-generated (Hibernate4)

### ISSUE THREAD

**Issue by robertoschwald** [liquibase/liquibase-hibernate#134]
With 3.6 (Hibernate4), existing indexes are always re-created:

Grails Entity:

```groovy
class UserRole implements Serializable {
	private static final long serialVersionUID = 1

	User user
	Role role

	static mapping = {
		cache true
		id composite:['role', 'user']
		version false
	}
}
```

Always leads to this diffs generated:

```groovy
databaseChangeLog = {

    changeSet(author: "rob (generated)", id: "1477901616435-1") {
        dropIndex(indexName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m", tableName: "user_role_eo")
    }

    changeSet(author: "rob (generated)", id: "1477901616435-2") {
        dropForeignKeyConstraint(baseTableName: "user_role_eo", constraintName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m")

        addForeignKeyConstraint(baseColumnNames: "user_da_id", baseTableName: "user_role_eo", constraintName: "FK_4tjo7nu3mr9j4b7pp0bt4ur3m", referencedColumnNames: "id_da", referencedTableName: "user_eo")
    }

    changeSet(author: "rob (generated)", id: "1477901616435-3") {
        dropForeignKeyConstraint(baseTableName: "user_role_eo", constraintName: "FK_f71rit4ced3vswl68lil7xhii")

        addForeignKeyConstraint(baseColumnNames: "role_da_id", baseTableName: "user_role_eo", constraintName: "FK_f71rit4ced3vswl68lil7xhii", referencedColumnNames: "id_da", referencedTableName: "role_eo")
    }
}
```

**Comment by gregdymek** [comment]
non composite also get regenerated everytime I run diff:
    <changeSet author="tete (generated)" id="1478626872055-42">
        <dropIndex indexName="user_customer_idx" tableName="users"/>
        <createIndex indexName="user_customer_idx" tableName="users">
            <column name="customer_id"/>
        </createIndex>
    </changeSet>
Once I run it again the same changeSet will be added to changeLog.xml
I'm using liquibase-hibernate5 version 3.6 from mvnrepository, with mysql db

**Comment by gregdymek** [comment]
isn't it something https://github.com/liquibase/liquibase-hibernate/commit/6db7aebb8d722f7a9a7b69bcdf7be2e0a1e201ba related ?

**Comment by Bert-R** [comment]
I'm facing this issue too. The database was generated through this:
```
    - addForeignKeyConstraint:
        baseColumnNames: interval_activity
        baseTableName: interval_activity_spread
        constraintName: FK_1am1vcdichgu2pec92pxfi2xg
        referencedColumnNames: id
        referencedTableName: interval_activities
```
Running ``diffChangeLog`` produces this change set:
```
- changeSet:
    id: 1478848634860-1
    author: Bert (generated)
    changes:
    - dropForeignKeyConstraint:
        baseTableName: interval_activity_spread
        constraintName: FK_1am1vcdichgu2pec92pxfi2xg
    - addForeignKeyConstraint:
        baseColumnNames: interval_activity
        baseTableName: interval_activity_spread
        constraintName: FK_1am1vcdichgu2pec92pxfi2xg
        referencedColumnNames: id
        referencedTableName: interval_activities
```

The foreign key constraint is exactly identical.

I'm using liquibase-hibernate 3.6, with HSQLDB and Spring.
