### ISSUE TITLE
Unable to generate sequence allocationSize

### ISSUE THREAD

**Issue by patanegra7** [liquibase/liquibase-hibernate#207]
With JPA / Hibernate 5.3.10 and liquibase 3.6.3 and liquibase-hibernate5 3.6:

I can't generate a sequence with an incrementBy value using the 'SequenceGenerator' annotation:

```
	@Id
	@SequenceGenerator(name = "AuthorSeq", sequenceName="author_seq", allocationSize=50 )
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="AuthorSeq")
	private Long id;
```

The allocationSize is ignored, so I get:

```
- changeSet:
    id: 1562326839357-2
    author: .......
    changes:
    - createSequence:
        sequenceName: author_seq

```

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-423) by [Unito](https://www.unito.io/learn-more)
