### ISSUE TITLE
Diff on OneToOne optional false

### ISSUE THREAD

**Issue by louis-neologix** [liquibase/liquibase-hibernate#219]
When I add the attribute optional to false on a OneToOne link : 

```java
@OneToOne(optional = false)
private Address address;
```

The diff changelog contains the following changesets :

```yaml
databaseChangeLog:
- changeSet:
    id: 1579006019496-2
    author: louis (generated)
    changes:
    - addUniqueConstraint:
        columnNames: address_id
        constraintName: UK_hdhcc7238a2lwr4yjw78qvlof
        tableName: contact
- changeSet:
    id: 1579006019496-1
    author: louis (generated)
    changes:
    - addNotNullConstraint:
        columnDataType: bigint
        columnName: address_id
        tableName: contact
```

Then, each time I generate the diff change log, it recreates the unique constraint :

```yaml
databaseChangeLog:
- changeSet:
    id: 1579006765086-1
    author: louis (generated)
    changes:
    - dropUniqueConstraint:
        constraintName: UK_hdhcc7238a2lwr4yjw78qvlof
        tableName: contact
    - addUniqueConstraint:
        columnNames: address_id
        constraintName: UK_hdhcc7238a2lwr4yjw78qvlof
        tableName: contact
```

If I use the liquidbase diff command, it display the following infos : 

```
Changed Unique Constraint(s): 
     UK_hdhcc7238a2lwr4yjw78qvlof on contact(address_id)
          clustered changed from 'null' to 'false'
```

Any idea of what cause this behavior ?

Thanks

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-412) by [Unito](https://www.unito.io/learn-more)
