### ISSUE TITLE
Maven plugin 'diff' generate addUniqueConstraint on PrimaryKey column

### ISSUE THREAD

**Issue by lanmaster** [liquibase/liquibase-hibernate#554]
Spring Boot application with Hibernate and PostgreSQL.
Entity:
```
@Getter
@Setter
@Entity
@Table(name = "document_status")
public class DocumentStatus {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, unique = true, updatable = false)
    private Long id;

    @Column(name = "name_full", unique = true)
    protected String nameFull;
}

```

I execute 'diff' from "liquibase-maven-plugin" that compare PostgreSQL database with Hibernate JPA structure.
Plugin code:
```
    <properties>
        <liquibase.version>4.23.2</liquibase.version>
        <maven.build.timestamp.format>yyyyMMdd_HHmmss</maven.build.timestamp.format>
    </properties>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase.version}</version>
                <configuration>
                    <diffExcludeObjects>
                        jv_commit_property, jv_global_id, jv_snapshot, jv_commit, sessions,
                        jv_snapshot_pk_seq, jv_global_id_pk_seq, jv_commit_pk_seq
                    </diffExcludeObjects>
                    <changeSetAuthor>cav</changeSetAuthor>
                    <changeLogFile>src/main/resources/db/changelog/db.changelog-master.yaml</changeLogFile>
                    <outputChangeLogFile>src/main/resources/db/changelog/temp/changelog_${maven.build.timestamp}.yaml
                    </outputChangeLogFile>
                    <diffChangeLogFile>
                        src/main/resources/db/changelog/temp/diff_changelog_${maven.build.timestamp}.yaml
                    </diffChangeLogFile>

                    <url>jdbc:postgresql://localhost:5432/workflow</url>
                    <driver>org.postgresql.Driver</driver>
                    <username>postgres</username>
                    <password>postgres</password>
                    <defaultSchemaName>public</defaultSchemaName>

                    <referenceUrl>
                        hibernate:spring:ru.sibintek.rodos?dialect=org.hibernate.dialect.PostgreSQL10Dialect&amp;hibernate.physical_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy&amp;hibernate.implicit_naming_strategy=org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
                    </referenceUrl>
                    <verbose>true</verbose>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.liquibase.ext</groupId>
                        <artifactId>liquibase-hibernate5</artifactId>
                        <version>4.22.0</version>
                    </dependency>
                    <dependency>
                        <groupId>org.springframework.boot</groupId>
                        <artifactId>spring-boot-starter-data-jpa</artifactId>
                        <version>2.7.3</version>
                    </dependency>

                    <dependency>
                        <groupId>javax.validation</groupId>
                        <artifactId>validation-api</artifactId>
                        <version>2.0.1.Final</version>
                    </dependency>

                </dependencies>
            </plugin>
```

Table creation script on app starting:
```
databaseChangeLog:
  - changeSet:
      id: 3
      author: cav
      changes:
        - createTable:
            tableName: document_status
            columns:
              - column:
                  name: id
                  type: BIGINT
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name_full
                  type: TEXT
```

Maven plugin generate diff:
```
databaseChangeLog:
- changeSet:
    id: 1695912841882-26
    author: cav
    changes:
    - addUniqueConstraint:
        columnNames: id
        constraintName: UC_DOCUMENT_STATUSID_COL
        tableName: document_status
```

If i add diff part to table creation script then i get two indexes on same column
```
CREATE TABLE public.document_status (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	is_deleted bool NOT NULL DEFAULT false,
	name_full text NULL,
	CONSTRAINT document_status_pkey PRIMARY KEY (id),
	CONSTRAINT uc_document_statusid_col UNIQUE (id)
);
```
![изображение](https://github.com/liquibase/liquibase-hibernate/assets/6203028/30cde52e-e925-45a9-92e5-a732003ad017)

How can i get diff that didn't generate "addUniqueConstraint" on column with PrimaryKey already exist?
